version: '3.8'

services:
  web_app_db:
    container_name: web_app_db
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - web_app_network
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  web_app:
    container_name: web_app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ylab_project:/app/app/
    env_file:
      - .env
    entrypoint: >
      sh -c "
        alembic upgrade head
        uvicorn main:app --host 0.0.0.0 --reload
      "
    networks:
      - web_app_network
    ports:
      - 8000:8000
    depends_on:
      web_app_db:
        condition: service_healthy

networks:
  web_app_network:
    name: web_app_network