version: '3.8'

services:
  web_app_db:
    container_name: web_app_db
    image: postgres:15.1-alpine
    volumes:
      - ./psql:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - web_app_network
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 5

  web_app_redis:
    container_name: web_app_redis
    image: redis:latest
    env_file:
      - .env
    networks:
      - web_app_network
    expose:
      - 6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10

  web_app:
    container_name: web_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - shared:/ylab_project/reports
    env_file:
      - .env
    entrypoint: >
      sh -c "
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --reload
      "
    networks:
      - web_app_network
    ports:
      - 8000:8000
    depends_on:
      web_app_db:
        condition: service_healthy
      web_app_redis:
        condition: service_healthy
      web_app_rabbit:
        condition: service_healthy

  web_app_rabbit:
    container_name: web_app_rabbit
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: '${RABBITMQ_VHOST}'
    env_file:
      - .env
    networks:
      - web_app_network
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test:  [ "CMD", "rabbitmqctl", "status" ]
      interval: 20s
      timeout: 10s
      retries: 10

  web_app_celery_worker:
    container_name: web_app_celery
    build: .
    volumes:
      - shared:/ylab_project/reports
    env_file:
      - .env
    networks:
      - web_app_network
    command: "celery -A app.v1.celery worker --loglevel=INFO"
    depends_on:
      web_app_redis:
        condition: service_healthy
      web_app_rabbit:
        condition: service_healthy
      web_app:
        condition: service_started

volumes:
  shared:


networks:
  web_app_network:
    name: web_app_network
