"""create tables

Revision ID: 52c1296501ee
Revises:
Create Date: 2023-02-03 12:58:34.495320

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '52c1296501ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'menus',
        sa.Column(
            'id', sa.Integer(),
            autoincrement=True, nullable=False,
        ),
        sa.Column('title', sa.String(length=200), nullable=True),
        sa.Column(
            'description', sa.String(
                length=1000,
            ), nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title'),
    )
    op.create_table(
        'submenus',
        sa.Column(
            'id', sa.Integer(),
            autoincrement=True, nullable=False,
        ),
        sa.Column('title', sa.String(length=200), nullable=True),
        sa.Column(
            'description', sa.String(
                length=1000,
            ), nullable=True,
        ),
        sa.Column('menu_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['menu_id'], ['menus.id'], ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title'),
    )
    op.create_table(
        'dishes',
        sa.Column(
            'id', sa.Integer(),
            autoincrement=True, nullable=False,
        ),
        sa.Column('title', sa.String(length=200), nullable=True),
        sa.Column(
            'description', sa.String(
                length=1000,
            ), nullable=True,
        ),
        sa.Column('submenu_id', sa.Integer(), nullable=False),
        sa.Column('price', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ['submenu_id'], ['submenus.id'], ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    op.drop_table('submenus')
    op.drop_table('menus')
    # ### end Alembic commands ###
