"""add submneus_count

Revision ID: 6b80bdadd2bf
Revises: 814bcbf2d767
Create Date: 2023-01-17 17:28:18.165119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b80bdadd2bf'
down_revision = '814bcbf2d767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
